
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { AppProviders } from "./providers";
import AppLayout from "./app-layout";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

 export const metadata = {
  title: "AVM Smiles",
  description: "Generated by create next app",
  icons: {
    icon: "/site-favicon.ico", // path in the public folder
  },
  
};


// const queryClient = new QueryClient();

export default function RootLayout({ children }) {
//     const [region, setRegion] = useState("0");
//     const [period, setPeriod] = useState("All");



//      const periods = [
//         { id: "D1", label: "Yesterday" },
//         { id: "W1", label: "Last 7 Days" },
//         { id: "M1", label: "30 Days" },
//         { id: "Q1", label: "90 Days" },
//         { id: "Y1", label: "365 Days" },
//         { id: "All", label: "Grouped" },
//       ];
//          const handleLogout = () => {
//   // Example logic — adjust for your app
//   localStorage.removeItem("token");
//     router.push("/"); 
// };

  return (
      <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} min-h-screen bg-background text-foreground antialiased`}
      >
           <AppProviders>
           <AppLayout>
        {children}
        </AppLayout>
        <ReactQueryDevtools initialIsOpen={false} />
     </AppProviders>

      </body>
    </html>
  );
}
